// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKG0unPPqXkGS1_Xxuki7-LSwwvI7YWos',
    appId: '1:1018193569060:web:ccb3d8e3d5677fa8d5ffb1',
    messagingSenderId: '1018193569060',
    projectId: 'librario-eb0d6',
    authDomain: 'librario-eb0d6.firebaseapp.com',
    storageBucket: 'librario-eb0d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb1Zuo8FoA3KmSKHKFEtfk9iGFQR67HgM',
    appId: '1:1018193569060:android:61e59d0a8887b799d5ffb1',
    messagingSenderId: '1018193569060',
    projectId: 'librario-eb0d6',
    storageBucket: 'librario-eb0d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6J_93D3fvynzHMJkKYdVk7Cr-F2JJlBQ',
    appId: '1:1018193569060:ios:1bf7e80d3ef68a60d5ffb1',
    messagingSenderId: '1018193569060',
    projectId: 'librario-eb0d6',
    storageBucket: 'librario-eb0d6.appspot.com',
    iosClientId: '1018193569060-292u9bsculo3scnmai10pbkirb2s194g.apps.googleusercontent.com',
    iosBundleId: 'wp.librario',
  );
}
